import * as THREE from "three";
import { useThree } from "@react-three/fiber";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VendingMachine(props) {
  const { nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}vending_machine.glb`
  );
  const { camera } = useThree();

  const screenRef = useRef();

  // const handleScreenClick = () => {
  //   const targetPos = new THREE.Vector3();

  //   if (screenRef.current) {
  //     screenRef.current.updateWorldMatrix(true, false);
  //     screenRef.current.getWorldPosition(targetPos);

  //     console.log(screenRef.current.getWorldPosition(targetPos));
  //   }
  //   const offset = new THREE.Vector3(0, 0, 1.5); // tweak distance
  //   const newCamPos = targetPos.clone().add(offset);

  //   gsap.to(camera.position, {
  //     x: newCamPos.x,
  //     y: newCamPos.y,
  //     z: newCamPos.z,
  //     duration: 1.5,
  //     ease: "power2.out",
  //     onUpdate: () => camera.lookAt(targetPos),
  //   });
  // };

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coin.geometry}
          material={materials.Black}
          position={[-0.408, 0.045, -0.428]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[0, -0.915, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.Main}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane026.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane030.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane036.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane037.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane038.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane040.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane042.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane043.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane044.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane045.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane046.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane048.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane049.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane052.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane053.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane054.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane055.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane056.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane057.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane058.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane059.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane060.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane061.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane062.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane063.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane065.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane068.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane069.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane071.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane072.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane073.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane074.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane075.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane076.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane077.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane078.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane079.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane080.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane082.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane083.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane084.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane085.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane086.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane087.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane089.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane090.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane091.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane092.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane093.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane094.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane095.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane096.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane097.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane098.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane099.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane100.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane101.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane102.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane103.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane105.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane106.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane107.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane108.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane109.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane110.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane112.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane113.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane114.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane115.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane116.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane117.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane118.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane119.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane120.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane121.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane122.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane123.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane124.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane125.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane126.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane127.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_3.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_4.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_5.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.Plate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials.Plate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials.Shelves}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}vending_machine.glb`);
