import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import { useTexture } from "@react-three/drei";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/Components/ui/dialog";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { projectsArray } from "./utils/projects";
import colors from "./utils/colors";

export function VendingMachine(props) {
  const { scene, nodes, materials } = useGLTF(
    `${import.meta.env.BASE_URL}vending_machine.glb`
  );

  const { handleOpenDialog } = props;

  const imgPaths = [
    `${import.meta.env.BASE_URL}retrogram.png`,
    `${import.meta.env.BASE_URL}catneed.png`,
    `${import.meta.env.BASE_URL}fitcommit.png`,
    `${import.meta.env.BASE_URL}babelbites.png`,
    `${import.meta.env.BASE_URL}othello.png`,
  ];
  const textures = useTexture(imgPaths);

  // const material = new THREE.MeshBasicMaterial({
  //   // color: "red",
  //   map: textures[0],
  //   transparent: true,
  //   side: THREE.DoubleSide,
  // });

  // const material2 = new THREE.MeshBasicMaterial({
  //   // color: "red",
  //   map: textures[1],
  //   transparent: true,
  //   side: THREE.DoubleSide,
  // });

  // const material3 = new THREE.MeshBasicMaterial({
  //   // color: "red",
  //   map: textures[2],
  //   transparent: true,
  //   side: THREE.DoubleSide,
  // });

  useEffect(() => {
    textures.forEach((texture, i) => {
      texture.minFilter = THREE.LinearMipMapLinearFilter;
      texture.magFilter = THREE.LinearFilter;
      // texture.wrapS = THREE.RepeatWrapping;
      // texture.wrapT = THREE.RepeatWrapping;
      texture.wrapS = THREE.ClampToEdgeWrapping;
      texture.wrapT = THREE.ClampToEdgeWrapping;
      texture.flipY = false; // Fix upside-down GLTF UV issue
      texture.encoding = THREE.sRGBEncoding; // Keep correct color space
      texture.needsUpdate = true;
    });
  }, [textures]);

  let screenMeshCount = 0;

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Coin.geometry}
          material={materials.Black}
          position={[-0.408, 0.045, -0.428]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group position={[0, -0.915, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Main}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.Main}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane004.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane008.geometry}
          material={materials.Plate}
          position={[0.395, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane012.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane016.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane020.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane024.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row01_Plane028.geometry}
          material={materials.Plate}
          position={[0.398, 0.579, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane001.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane005.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane009.geometry}
          material={materials.Plate}
          position={[0.235, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane013.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane017.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane021.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane025.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row02_Plane029.geometry}
          material={materials.Plate}
          position={[0.237, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane002.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane006.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane010.geometry}
          material={materials.Plate}
          position={[0.079, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane014.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane018.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane022.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane026.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row03_Plane030.geometry}
          material={materials.Plate}
          position={[0.081, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane003.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane007.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane011.geometry}
          material={materials.Plate}
          position={[-0.081, 0.579, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane015.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane019.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane023.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane027.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row04_Plane031.geometry}
          material={materials.Plate}
          position={[-0.079, 0.581, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane032.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane036.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane040.geometry}
          material={materials.Plate}
          position={[0.395, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane044.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane048.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane052.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane056.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row05_Plane060.geometry}
          material={materials.Plate}
          position={[0.398, 0.334, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane033.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane037.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane041.geometry}
          material={materials.Plate}
          position={[0.235, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane045.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane049.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane053.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane057.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row06_Plane061.geometry}
          material={materials.Plate}
          position={[0.237, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane034.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane038.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane042.geometry}
          material={materials.Plate}
          position={[0.079, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane046.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane050.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane054.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane058.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row07_Plane062.geometry}
          material={materials.Plate}
          position={[0.081, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane035.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane039.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane043.geometry}
          material={materials.Plate}
          position={[-0.081, 0.334, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane047.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane051.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane055.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane059.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row08_Plane063.geometry}
          material={materials.Plate}
          position={[-0.079, 0.337, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane064.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane068.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane072.geometry}
          material={materials.Plate}
          position={[0.395, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane076.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane080.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane084.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane088.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row09_Plane092.geometry}
          material={materials.Plate}
          position={[0.398, 0.088, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane065.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane069.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane073.geometry}
          material={materials.Plate}
          position={[0.235, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane077.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane081.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane085.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane089.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row10_Plane093.geometry}
          material={materials.Plate}
          position={[0.237, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane066.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane070.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane074.geometry}
          material={materials.Plate}
          position={[0.079, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane078.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane082.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane086.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane090.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row11_Plane094.geometry}
          material={materials.Plate}
          position={[0.081, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane067.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane071.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane075.geometry}
          material={materials.Plate}
          position={[-0.081, 0.088, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane079.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane083.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane087.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane091.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row12_Plane095.geometry}
          material={materials.Plate}
          position={[-0.079, 0.09, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane096.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane100.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane104.geometry}
          material={materials.Plate}
          position={[0.395, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane108.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane112.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane116.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane120.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row13_Plane124.geometry}
          material={materials.Plate}
          position={[0.398, -0.157, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane097.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane101.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane105.geometry}
          material={materials.Plate}
          position={[0.235, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane109.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane113.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane117.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane121.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row14_Plane125.geometry}
          material={materials.Plate}
          position={[0.237, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane098.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane102.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane106.geometry}
          material={materials.Plate}
          position={[0.079, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane110.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane114.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane118.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane122.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row15_Plane126.geometry}
          material={materials.Plate}
          position={[0.081, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane099.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.182]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane103.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.122]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane107.geometry}
          material={materials.Plate}
          position={[-0.081, -0.157, 0.062]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane111.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, 0.002]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane115.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.058]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane119.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.118]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane123.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.178]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Row16_Plane127.geometry}
          material={materials.Plate}
          position={[-0.079, -0.154, -0.238]}
          rotation={[-1.309, 0, 0]}
          scale={[0.5, 1, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_3.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_4.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_5.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen001_1.geometry}
          material={materials.Shelves}
        />

        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen001_2.geometry}
          material={material}
          onClick={() => handleOpenDialog("virtual-garden")}
        /> */}

        {Object.entries(nodes).map(([key, node]) => {
          if (!node.geometry || !node.material.name.includes("Screen"))
            return null;

          const index = screenMeshCount;
          screenMeshCount += 1;

          return (
            <mesh
              key={key}
              geometry={node.geometry}
              material={new THREE.MeshBasicMaterial({ color: colors[index] })}
              // material={node.material}
              userData={{ index, projectName: projectsArray[index] }}
              castShadow
              receiveShadow
              onClick={(event) => {
                event.stopPropagation();
                const mesh = event.object;
                console.log("Clicked mesh:", mesh.userData);
                handleOpenDialog(mesh.userData.projectName);
              }}
            />
          );
        })}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002_1.geometry}
          material={materials.Shelves}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen002_2.geometry}
          material={material2}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen003_1.geometry}
          material={materials.Shelves}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen003_2.geometry}
          material={material3}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen004_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen004_2.geometry}
          // material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen005_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen005_2.geometry}
          // material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen006_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen006_2.geometry}
          // material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen007_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen007_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen008_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen008_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen009_1.geometry}
          material={materials.Plate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen009_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen010_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen010_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen011_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen011_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen012_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen012_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen013_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen013_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen014_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen014_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen015_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen015_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen016_1.geometry}
          material={materials.Shelves}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen016_2.geometry}
          material={materials.Screen}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${import.meta.env.BASE_URL}vending_machine.glb`);
